### ISSUE TITLE
`Vim(call):E718: Funcref required` error when using `:SCNvimFuzzyDef`

### ISSUE THREAD

**Issue by vitreo12** [madskjeldgaard/supercollider-h4x-nvim#1]
Hello Mads!

I'm getting this error whenever I try to open a Class with `:SCNvimFuzzyDef`:
```
...plugged/supercollider-h4x-nvim/lua/supercollider-...empt to concatenate local 'lookup_path' (a nil value)
Error detected while processing function 288[30]..<SNR>59_callback:
line   23:
Vim(call):E718: Funcref required
Press ENTER or type command to continue
```

Am I perhaps doing something wrong or there's a bug here?

Keep up the great work! :)

**Comment by madskjeldgaard** [comment]
Hi ! Thanks for the heads up. there definately was a bug here and I think it is fixed now. If you pull the latest version you will get it fixed I think. Just FYI - the fuzzy functions are being moved to this independent plugin at some point soon but the one's from this one will probably work for a while :) 

https://github.com/madskjeldgaard/fzf-sc

**Comment by vitreo12** [comment]
Great, thanks!

However, there is one more problem I'm noticing. The fuzzy find won't open files contained in `Extensions` folders, as it seems that it is skipping the `~` home path handling. 

For example, instead of opening `~/.local/share/SuperCollider/Extensions/MyFile.sc`, the plugin will try to load (and failing, displaying an empty buffer) `.local/share/SuperCollider/Extensions/MyFile.sc`.
